- name: Retrieve argocd record
  amazon.aws.route53:
    state: get
    zone: "{{ dns.zone }}"
    record: "{{ argo_suffix + '.' + dns.base_host }}"
    type: A
  register: rec

- name: Remove argocd record
  community.aws.route53:
    state: absent
    zone: "{{ dns.zone }}"
    record: "{{ rec.set.record }}"
    type: "{{ rec.set.type }}"
    value: "{{ rec.set.value }}"
    alias: true
    alias_hosted_zone_id: "Z3Q77PNBQS71R4"
  when: rec.set['record'] is defined

- name: Retrieve argocd-grpc API record
  amazon.aws.route53:
    state: get
    zone: "{{ dns.zone }}"
    record: "{{ argo_grpc_suffix + '.' + dns.base_host }}"
    type: A
  register: rec

- name: Remove argocd-grpc API record
  community.aws.route53:
    state: absent
    zone: "{{ dns.zone }}"
    record: "{{ rec.set.record }}"
    type: "{{ rec.set.type }}"
    value: "{{ rec.set.value }}"
    alias: true
    alias_hosted_zone_id: "Z3Q77PNBQS71R4"
  when: rec.set['record'] is defined
